### ISSUE TITLE
Animated gifs cause an exception

### ISSUE THREAD

**Issue by robertoszek** [robertoszek/pleroma-twitter-info-grabber#13]
When a tweet includes an attachment of type 'animated_gif' it causes an exception.
```
Traceback (most recent call last):
  File "pleroma-twitter-info-grabber/updateInfoPleroma.py", line 710, in <module>
    main()
  File "pleroma-twitter-info-grabber/updateInfoPleroma.py", line 673, in main
    tweets_to_post = user.process_tweets(tweets_to_post)
  File "pleroma-twitter-info-grabber/updateInfoPleroma.py", line 372, in process_tweets
    media_url = item['url']
KeyError: 'url'
```

**Comment by robertoszek** [comment]
Treat the animated gifs the same way as videos (as the download URL is simply a .mp4 file), using v1.1.
https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/1bbccb441d2133477e431a6ab27382d44c486389
