### ISSUE TITLE
Twitter API v2

### ISSUE THREAD

**Issue by 1337god** [robertoszek/pleroma-twitter-info-grabber#31]
```pleroma_bot - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/joker/.local/lib/python3.8/site-packages/pleroma_bot/cli.py", line 209, in main
    user = User(user_item, config)
  File "/home/joker/.local/lib/python3.8/site-packages/pleroma_bot/cli.py", line 171, in __init__
    self.tweets = self._get_tweets("v2")
  File "/home/joker/.local/lib/python3.8/site-packages/pleroma_bot/_twitter.py", line 122, in _get_tweets
    response.raise_for_status()
  File "/home/joker/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/tweets/search/recent?max_results=40&query=from%3Aparlamentopt&poll.fields=duration_minutes%2Cend_datetime%2Cid%2Coptions%2Cvoting_status&media.fields=duration_ms%2Cheight%2Cmedia_key%2Cpreview_image_url%2Ctype%2Curl%2Cwidth%2Cpublic_metrics&expansions=attachments.poll_ids%2Cattachments.media_keys%2Cauthor_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld
```
API v2?

**Comment by 1337god** [comment]
Had to make a new App due to new twitter changes.

**Comment by nemobis** [comment]
> Had to make a new App due to new twitter changes.

For me it was enough to make sure that the old app  was part of a project:

> If you would like to use the new Twitter API v2 endpoints, you will need to make sure that the developer App is within a Project.

https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens#Prerequisites

Maybe this should be mentioned in the docs.
